### ISSUE TITLE
"Blur switch" Fehlfunktion?

### ISSUE THREAD

**Issue by MarcTschudin** [hidden-beauty/hiddenbeauty-web#1]
**https://hiddenbeauty.ch/**
 - Blur switch ist beim laden der Seite “aus” —> Absicht? - die “unblur buttons” funktionieren erst nach dem zweiten Klick
 
 **https://hiddenbeauty.ch/exhibit/**
Bilder sind nicht verpixelt, obwohl der Button oben rechts auf “on” ist (wurde beim Aufrufen der Seite gleich eingeschaltet und dann nicht mehr gedrückt”.
wird der Button auf “Off” geschaltet, verpixeln alle Bilder.

 **https://hiddenbeauty.ch/model/352392-PLNN-1**
Show unblured model? (WARNING message)
Die Nachricht kam erst bei Anrufen des 3. Modelle (geschätzt), vorher nicht.
 - Nach Klicken von “agree” wurde das Modell angezeigt, die Bilder unten (Vorschau anderer Modelle) ist aber immer noch verpixelt.  Der Button “Blur images” ist auf OFF.
  
  - Beim zurück Springen auf die Einstiegsseite wird der Blur-Button auf ON gesetzt, die Bilder unten werden aber nicht verpixelt
  
**https://hiddenbeauty.ch/model/790518-VSNN**
WARNING message (Der Button “Blur images” ist schon auf OFF.)  Problem: Die Bilder unten sind verpixelt.

**Comment by mayhem** [comment]
Yup, da steckten ein paar doofe sachen drin. Fixed.
