### ISSUE TITLE
inactive hyperlinks?

### ISSUE THREAD

**Issue by MarcTschudin** [hidden-beauty/hiddenbeauty-web#3]
**https://hiddenbeauty.ch/browse/by-model**
Die Tags in der Mitte des Bildschirms haben keinen Hyperlink (anklicken hat keine Funktion —> so gewollt?)
Tags am Bildschirmrand (rechts) haben Hyperlink

**Comment by mayhem** [comment]
Good find, habe aber kein bock das zu fixen.
