### ISSUE TITLE
Formating change?

### ISSUE THREAD

**Issue by MarcTschudin** [hidden-beauty/hiddenbeauty-web#6]
**https://hiddenbeauty.ch/docs/guide**
“Click on the image to reveal the answers.” 
**Fett** machen? 

Nur unter dem ersten Bild, dann wird das etwas besser hervorgehoben. einige haben bei der ersten Version der HP schon nicht gemerkt, dass man auf das Bild klicken kann...

**Comment by mayhem** [comment]
Done.
